version: "2.1"
services:
  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /airsonic/config:/config
      - /airsonic/music:/music
      - /airsonic/playlists:/playlists
      - /airsonic/podcasts:/podcasts
    ports:
      - 4040:4040
    restart: unless-stopped
